name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Copy SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Create Ansible Vault password file
        run: echo "$ANSIBLE_VAULT_PASS" > vault_pass.txt
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts_enc.yaml playbook.yaml --vault-password-file vault_pass.txt

      - name: Clean up vault file
        run: rm -f vault_pass.txt

